INSERT INTO characters(parent_id,name,color) VALUES (0,'Warrior','red');
INSERT INTO characters(parent_id,name,color) VALUES (0,'Wizard','green');
INSERT INTO characters(parent_id,name,color) VALUES (0,'Priest','white');
INSERT INTO characters(parent_id,name,color) VALUES (0,'Rogue','yellow');
INSERT INTO characters(parent_id,name,color) VALUES (1,'Fighter','blue');
INSERT INTO characters(parent_id,name,color) VALUES (1,'Paladin','lighblue');
INSERT INTO characters(parent_id,name,color) VALUES (1,'Ranger','lighgreen');
INSERT INTO characters(parent_id,name,color) VALUES (2,'Mage','grey');
INSERT INTO characters(parent_id,name,color) VALUES (2,'Specialist wizard','lightgrey');
INSERT INTO characters(parent_id,name,color) VALUES (3,'Cleric','red');
INSERT INTO characters(parent_id,name,color) VALUES (3,'Druid','green');
INSERT INTO characters(parent_id,name,color) VALUES (3,'Priest of specific mythos','white');
INSERT INTO characters(parent_id,name,color) VALUES (4,'Thief','yellow');
INSERT INTO characters(parent_id,name,color) VALUES (4,'Bard','blue');
INSERT INTO characters(parent_id,name,color) VALUES (13,'Assassin','lighblue');
